# -*- coding: utf-8 -*-
"""ACC-aftermath.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zs02Emz0iMSpDo6GUFtIy1B8G_8Fd6ri
"""

# fix domain shit - by doing SMOTE

!pip install -q scikit-learn scipy matplotlib seaborn tensorflow imbalanced-learn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.signal import find_peaks, resample
from scipy.stats import skew, kurtosis
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from imblearn.over_sampling import SMOTE
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Conv1D, MaxPooling1D, Input
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical
from google.colab import files
import warnings, pickle
warnings.filterwarnings('ignore')

LABELS = ['Forehand', 'Backhand', 'Serve']
print(" Ready — accel_v4 (normalised + SMOTE)")


print("=" * 55)
print("UPLOAD HOME SESSIONS (training data)")
print("=" * 55)

print("\nUpload Home Session 1: Tennis_1.csv")
u1 = files.upload(); S1_FILE = list(u1.keys())[0]; print(f" {S1_FILE}")

print("\nUpload Home Session 2: tennis_data_2.csv")
u2 = files.upload(); S2_FILE = list(u2.keys())[0]; print(f" {S2_FILE}")

print("\nUpload Home Session 3: tennis_data_3.csv")
u3 = files.upload(); S3_FILE = list(u3.keys())[0]; print(f" {S3_FILE}")

print("\n" + "=" * 55)
print("UPLOAD COURT SESSIONS")
print("=" * 55)

print("\nUpload Court Session 1 (TRAINING): results_1.csv")
u4 = files.upload(); C1_FILE = list(u4.keys())[0]; print(f" {C1_FILE}")

print("\nUpload Court Session 2 (TEST — Player 1): results_2.csv")
u5 = files.upload(); C2_FILE = list(u5.keys())[0]; print(f" {C2_FILE}")

print("\nUpload Court Session 3 (TEST — Player 2): results_3.csv")
u6 = files.upload(); C3_FILE = list(u6.keys())[0]; print(f" {C3_FILE}")

print(f"\n All 6 files loaded")
print(f"  TRAIN: {S1_FILE}, {S2_FILE}, {S3_FILE}, {C1_FILE}")
print(f"  TEST:  {C2_FILE} (Player 1), {C3_FILE} (Player 2)")


CLIP_SEC  = 0.6
N_SAMPLES = 60

def load_csv(path):
    df = pd.read_csv(path, comment='#')
    df.columns = ['time', 'ax', 'ay', 'az', 'aT']
    return df

def detect_swings(df, t0, t1, threshold, min_dist=55):
    sec = df[(df.time >= t0) & (df.time < t1)].copy()
    if len(sec) == 0:
        return np.array([]), np.array([])
    peaks, _ = find_peaks(sec['aT'].values, height=threshold, distance=min_dist)
    return sec['time'].iloc[peaks].values, sec['aT'].iloc[peaks].values

def get_clip(df, t_center, clip_sec=CLIP_SEC):
    t0   = t_center - clip_sec / 2
    t1   = t_center + clip_sec / 2
    clip = df[(df.time >= t0) & (df.time < t1)]
    return clip if len(clip) >= 20 else None

# NORMALISED FEATURES

def handcrafted_features(clip):
    feats = []
    for col in ['ax', 'ay', 'az', 'aT']:
        sig      = clip[col].values
        peak_val = np.max(np.abs(sig)) + 1e-8


        sig_norm = sig / peak_val
        feats += [
            np.mean(sig_norm),
            np.std(sig_norm),
            np.max(sig_norm),
            np.min(sig_norm),
            np.max(sig_norm) - np.min(sig_norm),
            float(skew(sig_norm)),
            float(kurtosis(sig_norm)),
        ]

        feats += [
            peak_val,
            np.sqrt(np.mean(sig**2)),
        ]


    aT  = clip['aT'].values
    ax  = clip['ax'].values
    feats.append(np.max(aT))
    feats.append(float(np.sum(np.diff(np.sign(ax)) != 0)) / len(ax))
    feats.append(np.sum(aT**2) / len(aT))


    mean_ax = np.mean(np.abs(clip['ax'].values))
    mean_ay = np.mean(np.abs(clip['ay'].values))
    mean_az = np.mean(np.abs(clip['az'].values))
    total   = mean_ax + mean_ay + mean_az + 1e-8
    feats.append(mean_ax / total)
    feats.append(mean_ay / total)
    feats.append(mean_az / total)

    return np.array(feats, dtype=np.float32)

def raw_window(df, t_center):
    clip = get_clip(df, t_center)
    if clip is None:
        return None
    raw = clip[['ax', 'ay', 'az', 'aT']].values

    raw_norm = raw / (np.max(np.abs(raw), axis=0) + 1e-8)
    return resample(raw_norm, N_SAMPLES, axis=0).astype(np.float32)

def extract_from_timestamps(df, times, labels_list):
    X_f, X_r, y = [], [], []
    for t, lab in zip(times, labels_list):
        clip = get_clip(df, t)
        rw   = raw_window(df, t)
        if clip is None or rw is None:
            print(f"Skipped t={t:.2f}s (clip too short)")
            continue
        X_f.append(handcrafted_features(clip))
        X_r.append(rw)
        y.append(lab)
    return X_f, X_r, y

print(" Helper functions defined")
print(f"   Feature vector size: {len(handcrafted_features(pd.DataFrame({'ax':[1]*20,'ay':[1]*20,'az':[1]*20,'aT':[1]*20})))} features")


df1 = load_csv(S1_FILE)
df2 = load_csv(S2_FILE)
df3 = load_csv(S3_FILE)

f1, _ = detect_swings(df1,   0,  40, 25)
b1, _ = detect_swings(df1,  40,  83, 25)
s1, _ = detect_swings(df1,  83, 999, 50)
f2, _ = detect_swings(df2,   0,  83, 30)
b2, _ = detect_swings(df2,  83, 185, 30)
s2, _ = detect_swings(df2, 185, 999, 70)
f3, _ = detect_swings(df3,   0, 130, 30)
b3, _ = detect_swings(df3, 130, 280, 30)
s3, _ = detect_swings(df3, 280, 999, 60)

print(f"Home S1: F={len(f1)}  B={len(b1)}  S={len(s1)}")
print(f"Home S2: F={len(f2)}  B={len(b2)}  S={len(s2)}")
print(f"Home S3: F={len(f3)}  B={len(b3)}  S={len(s3)}")

all_f = [(t,df1) for t in f1]+[(t,df2) for t in f2]+[(t,df3) for t in f3]
all_b = [(t,df1) for t in b1]+[(t,df2) for t in b2]+[(t,df3) for t in b3]
all_s = [(t,df1) for t in s1]+[(t,df2) for t in s2]+[(t,df3) for t in s3]
N     = min(len(all_f), len(all_b), len(all_s))
all_f, all_b, all_s = all_f[:N], all_b[:N], all_s[:N]
print(f"\n Home balanced: {N} per class = {N*3} total")

X_feat, X_raw, y_all, source = [], [], [], []
for label, pairs in enumerate([all_f, all_b, all_s]):
    for (t, df) in pairs:
        clip = get_clip(df, t)
        rw   = raw_window(df, t)
        if clip is None or rw is None:
            continue
        X_feat.append(handcrafted_features(clip))
        X_raw.append(rw)
        y_all.append(label)
        source.append('home')

home_count = len(y_all)
print(f"Home features extracted: {home_count}")


df_c1 = load_csv(C1_FILE)

COURT1_TIMES  = [7.18, 22.73, 26.06, 29.50, 39.51,
                 42.66, 45.62, 54.98, 58.26, 66.71, 69.25]
COURT1_LABELS = [2, 2, 1, 0, 0, 1, 0, 2, 0, 2, 0]

xf_c1, xr_c1, y_c1 = extract_from_timestamps(df_c1, COURT1_TIMES, COURT1_LABELS)
X_feat += xf_c1
X_raw  += xr_c1
y_all  += y_c1
source += ['court'] * len(y_c1)

court1_count = len(y_c1)
print(f"Court Session 1 added: {court1_count} samples")
print(f"  F={y_c1.count(0)}  B={y_c1.count(1)}  S={y_c1.count(2)}")

X_feat = np.array(X_feat, dtype=np.float32)
X_raw  = np.array(X_raw,  dtype=np.float32)
y_all  = np.array(y_all)

print(f"\nBefore SMOTE: {len(y_all)} total")
print(f"  F={np.sum(y_all==0)}  B={np.sum(y_all==1)}  S={np.sum(y_all==2)}")

# SMOTE
X_home = X_feat[np.array(source) == 'home']
y_home = y_all[np.array(source) == 'home']
X_court= X_feat[np.array(source) == 'court']
y_court= y_all[np.array(source) == 'court']

print(f"\nApplying SMOTE to court data...")
print(f"  Before: F={np.sum(y_court==0)} B={np.sum(y_court==1)} S={np.sum(y_court==2)}")


court_target = {}
for cls in [0, 1, 2]:
    n = np.sum(y_court == cls)
    court_target[cls] = max(n * 3, 6)

try:
    sm = SMOTE(sampling_strategy=court_target, k_neighbors=min(2, min(np.sum(y_court==c) for c in [0,1,2])-1), random_state=42)
    X_court_sm, y_court_sm = sm.fit_resample(X_court, y_court)
    print(f"  After SMOTE: F={np.sum(y_court_sm==0)} B={np.sum(y_court_sm==1)} S={np.sum(y_court_sm==2)}")
except Exception as e:
    print(f"  SMOTE fallback (manual tripling): {e}")
    X_court_sm = np.tile(X_court, (3, 1))
    y_court_sm = np.tile(y_court, 3)
    print(f"  After tripling: F={np.sum(y_court_sm==0)} B={np.sum(y_court_sm==1)} S={np.sum(y_court_sm==2)}")


X_combined = np.vstack([X_home, X_court_sm])
y_combined = np.concatenate([y_home, y_court_sm])

print(f"\n FINAL TRAINING DATA (after SMOTE)")
print(f"  Home:   {len(X_home)} samples  (×1)")
print(f"  Court:  {len(X_court_sm)} samples (×3 via SMOTE)")
print(f"  Total:  {len(X_combined)}")
print(f"  F={np.sum(y_combined==0)}  B={np.sum(y_combined==1)}  S={np.sum(y_combined==2)}")


df_c2 = load_csv(C2_FILE)
df_c3 = load_csv(C3_FILE)

COURT2_TIMES  = [16.67,19.25,25.77,29.06,31.81,
                 35.82,54.31,57.32,60.98,64.54,
                 67.47,71.10,72.20]
COURT2_LABELS = [2,0,2,0,0,1,2,2,1,0,0,1,0]

COURT3_TIMES  = [11.89,15.04,19.11,23.47,27.50]
COURT3_LABELS = [2,0,1,0,0]

xf_c2, xr_c2, y_c2 = extract_from_timestamps(df_c2, COURT2_TIMES, COURT2_LABELS)
xf_c3, xr_c3, y_c3 = extract_from_timestamps(df_c3, COURT3_TIMES, COURT3_LABELS)

print(f"Test — Court P1: {len(y_c2)} samples")
print(f"Test — Court P2: {len(y_c3)} samples (cross-player)")


scaler     = StandardScaler()
X_scaled   = scaler.fit_transform(X_combined)

svm = SVC(kernel='rbf', C=10, gamma='scale',
          probability=True, class_weight='balanced',
          random_state=42)

cv         = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
svm_scores = cross_val_score(svm, X_scaled, y_combined, cv=cv, scoring='accuracy')

print("=" * 55)
print("SVM v4 — Normalised + SMOTE + Balanced Weights")
print("5-Fold Cross Validation")
print("=" * 55)
print(f"  Per-fold : {np.round(svm_scores*100, 1)}")
print(f"  Mean CV  : {svm_scores.mean()*100:.1f}%")
print(f"  Std      : ±{svm_scores.std()*100:.1f}%")


svm.fit(X_scaled, y_combined)


X_c2_sc = scaler.transform(xf_c2)
X_c3_sc = scaler.transform(xf_c3)

y_pred_c2 = svm.predict(X_c2_sc)
y_pred_c3 = svm.predict(X_c3_sc)
acc_c2    = accuracy_score(y_c2, y_pred_c2) * 100
acc_c3    = accuracy_score(y_c3, y_pred_c3) * 100

svm_cv  = svm_scores.mean() * 100
svm_std = svm_scores.std()  * 100

print(f"\nCourt Test P1 (Player 1): {acc_c2:.1f}%")
print(classification_report(y_c2, y_pred_c2, target_names=LABELS, zero_division=0))
print(f"Court Test P2 (Player 2 cross-player): {acc_c3:.1f}%")
print(classification_report(y_c3, y_pred_c3, target_names=LABELS, zero_division=0))


cv_split    = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
tr_i, te_i  = list(cv_split.split(X_scaled, y_combined))[-1]
svm_tmp     = SVC(kernel='rbf', C=10, gamma='scale', probability=True,
                  class_weight='balanced', random_state=42)
svm_tmp.fit(X_scaled[tr_i], y_combined[tr_i])
y_pred_home = svm_tmp.predict(X_scaled[te_i])
cm_home     = confusion_matrix(y_combined[te_i], y_pred_home)
cm_c2       = confusion_matrix(y_c2, y_pred_c2)
cm_c3       = confusion_matrix(y_c3, y_pred_c3)

fig, axes = plt.subplots(1, 3, figsize=(17, 5))
home_acc = accuracy_score(y_combined[te_i], y_pred_home)*100
infos = [
    (cm_home, f'Home CV (fold 5)\n{home_acc:.0f}%',  'Blues'),
    (cm_c2,   f'Court — Player 1\n{acc_c2:.0f}%',    'Greens'),
    (cm_c3,   f'Court — Player 2\n(Cross-Player) {acc_c3:.0f}%', 'Oranges'),
]
for ax, (cm, title, cmap) in zip(axes, infos):
    sns.heatmap(cm, annot=True, fmt='d', cmap=cmap,
                xticklabels=LABELS, yticklabels=LABELS,
                linewidths=0.5, ax=ax, annot_kws={"size":13})
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')

plt.suptitle('SVM v4 — Normalised Features + SMOTE\n3-Tier: Home → Court → Cross-Player',
             fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('svm_v4_confusion.png', dpi=150, bbox_inches='tight')
plt.show()
print(" svm_v4_confusion.png saved")

X_raw_home   = X_raw[:home_count]
y_raw_home   = y_all[:home_count]
X_raw_court1 = X_raw[home_count:]
y_raw_court1 = y_all[home_count:]


X_raw_court3 = np.tile(X_raw_court1, (3, 1, 1))
y_raw_court3 = np.tile(y_raw_court1, 3)

X_raw_all = np.vstack([X_raw_home, X_raw_court3])
y_raw_all  = np.concatenate([y_raw_home, y_raw_court3])

y_cat = to_categorical(y_raw_all, 3)
X_tr_r, X_te_r, y_tr_r, y_te_r, y_tr_i, y_te_i = train_test_split(
    X_raw_all, y_cat, y_raw_all,
    test_size=0.2, stratify=y_raw_all, random_state=42)

model = Sequential([
    Input(shape=(N_SAMPLES, 4)),
    Conv1D(32, kernel_size=5, activation='relu', padding='same'),
    MaxPooling1D(2), Dropout(0.3),
    Conv1D(64, kernel_size=3, activation='relu', padding='same'),
    MaxPooling1D(2), Dropout(0.3),
    LSTM(64, return_sequences=True), Dropout(0.4),
    LSTM(32, return_sequences=False), Dropout(0.4),
    Dense(32, activation='relu'), Dropout(0.3),
    Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    X_tr_r, y_tr_r,
    validation_data=(X_te_r, y_te_r),
    epochs=150, batch_size=8,
    callbacks=[EarlyStopping(patience=20, restore_best_weights=True, verbose=0)],
    verbose=1
)

y_pred_cnn_val = np.argmax(model.predict(X_te_r, verbose=0), axis=1)
cnn_val        = max(history.history['val_accuracy']) * 100

X_raw_c2 = np.array(xr_c2)
X_raw_c3 = np.array(xr_c3)
y_pred_cnn_c2 = np.argmax(model.predict(X_raw_c2, verbose=0), axis=1)
y_pred_cnn_c3 = np.argmax(model.predict(X_raw_c3, verbose=0), axis=1)
cnn_acc_c2    = accuracy_score(y_c2, y_pred_cnn_c2) * 100
cnn_acc_c3    = accuracy_score(y_c3, y_pred_cnn_c3) * 100

print(f"\nCNN-LSTM val accuracy : {cnn_val:.1f}%")
print(f"CNN-LSTM Court P1     : {cnn_acc_c2:.1f}%")
print(f"CNN-LSTM Court P2     : {cnn_acc_c3:.1f}%")


fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history.history['accuracy'],     label='Train', color='#2E75B6', lw=2)
axes[0].plot(history.history['val_accuracy'], label='Val',   color='#00C878', lw=2)
axes[0].set_title('Accuracy', fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].legend(); axes[0].grid(True, alpha=0.3)
axes[1].plot(history.history['loss'],         label='Train', color='#2E75B6', lw=2)
axes[1].plot(history.history['val_loss'],     label='Val',   color='#E74C3C', lw=2)
axes[1].set_title('Loss', fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].legend(); axes[1].grid(True, alpha=0.3)
plt.suptitle('CNN-LSTM v4 Training — Normalised + Court Data ×3', fontweight='bold')
plt.tight_layout()
plt.savefig('cnnlstm_curves_v4.png', dpi=150)
plt.show()


winner = "SVM" if svm_cv >= cnn_val else "CNN-LSTM"

print("\n" + "═" * 65)
print("FINAL RESULTS — SVM v4 vs CNN-LSTM v4")
print("═" * 65)
print(f"{'Evaluation':<38} {'SVM v4':>8}  {'CNN-LSTM':>10}")
print("-" * 65)
print(f"{'Home 5-Fold CV (combined data)':<38} {svm_cv:>6.1f}%  {cnn_val:>8.1f}%")
print(f"{'Court Test — Player 1 (unseen session)':<38} {acc_c2:>6.1f}%  {cnn_acc_c2:>8.1f}%")
print(f"{'Court Test — Player 2 (cross-player)':<38} {acc_c3:>6.1f}%  {cnn_acc_c3:>8.1f}%")
print("═" * 65)

x     = np.arange(3)
w     = 0.35
tiers = ['Home\n5-Fold CV', 'Court\nPlayer 1', 'Court\nPlayer 2\n(Cross-Player)']
svm_v = [svm_cv,    acc_c2,    acc_c3]
cnn_v = [cnn_val,   cnn_acc_c2, cnn_acc_c3]

fig, ax = plt.subplots(figsize=(11, 6))
b1 = ax.bar(x - w/2, svm_v, w, label='SVM (RBF) v4',  color='#2E75B6',
            yerr=[svm_std, 0, 0], capsize=6, error_kw={'lw':2})
b2 = ax.bar(x + w/2, cnn_v, w, label='CNN-LSTM v4',    color='#00C878')

for bar, val in zip(list(b1)+list(b2), svm_v+cnn_v):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+1.8,
            f'{val:.0f}%', ha='center', fontsize=11, fontweight='bold')

ax.set_xticks(x); ax.set_xticklabels(tiers, fontsize=11)
ax.set_ylim(0, 115)
ax.set_ylabel('Accuracy (%)', fontsize=12)
ax.set_title('Accelerometer v4 — SVM vs CNN-LSTM\nNormalised Features + SMOTE Court Oversampling',
             fontsize=13, fontweight='bold')
ax.axhline(80, color='red', ls='--', lw=1.5, alpha=0.5, label='80% baseline')
ax.legend(fontsize=11); ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig('accel_v4_comparison.png', dpi=150)
plt.show()
print(" accel_v4_comparison.png saved")


def print_stroke_table(times, y_true, y_pred_svm, y_pred_cnn, probs, title):
    print("\n" + "=" * 68)
    print(title)
    print("=" * 68)
    print(f"{'#':<3} {'Time':>7}  {'True':>10}  {'SVM':>10}  {'CNN':>10}  {'Conf':>7}  {'✓/✗'}")
    print("-" * 68)
    for i,(t,yt,ys,yc) in enumerate(zip(times,y_true,y_pred_svm,y_pred_cnn)):
        conf  = probs[i][ys]*100
        match = '✅' if yt==ys else '❌'
        print(f"{i+1:<3} {t:>6.2f}s  {LABELS[yt]:>10}  {LABELS[ys]:>10}  "
              f"{LABELS[yc]:>10}  {conf:>5.1f}%  {match}")
    n_correct = sum(a==b for a,b in zip(y_true,y_pred_svm))
    print(f"\nSVM:     {n_correct}/{len(y_true)} correct = {n_correct/len(y_true)*100:.1f}%")
    print(f"CNN-LSTM:{sum(a==b for a,b in zip(y_true,y_pred_cnn))}/{len(y_true)} correct = "
          f"{sum(a==b for a,b in zip(y_true,y_pred_cnn))/len(y_true)*100:.1f}%")

probs_c2 = svm.predict_proba(X_c2_sc)
probs_c3 = svm.predict_proba(X_c3_sc)

print_stroke_table(COURT2_TIMES, y_c2, y_pred_c2, y_pred_cnn_c2, probs_c2,
                   "COURT SESSION 2 — Player 1 (unseen court session)")
print_stroke_table(COURT3_TIMES, y_c3, y_pred_c3, y_pred_cnn_c3, probs_c3,
                   "COURT SESSION 3 — Player 2 (cross-player test)")

svm.fit(X_scaled, y_combined)
with open('accel_svm_v4.pkl', 'wb') as f:
    pickle.dump({
        'model':          svm,
        'scaler':         scaler,
        'svm_cv':         svm_cv,
        'svm_std':        svm_std,
        'acc_court_p1':   acc_c2,
        'acc_court_p2':   acc_c3,
        'cnn_val':        cnn_val,
        'winner':         winner,
        'n_features':     X_combined.shape[1],
        'training_total': len(y_combined),
        'home_samples':   len(X_home),
        'court_smote':    len(X_court_sm),
    }, f)
model.save('accel_cnn_lstm_v4.h5')

print("\n" + "═"*60)
print(" COPY INTO REPORT")
print("═"*60)
print(f"  Training: {len(y_combined)} total ({len(X_home)} home + {len(X_court_sm)} court×3 SMOTE)")
print(f"  Features per sample: {X_combined.shape[1]}")
print(f"  SVM 5-Fold CV:       {svm_cv:.1f}% ±{svm_std:.1f}%")
print(f"  SVM Court P1:        {acc_c2:.1f}%  ({int(acc_c2/100*len(y_c2))}/{len(y_c2)})")
print(f"  SVM Court P2:        {acc_c3:.1f}%  ({int(acc_c3/100*len(y_c3))}/{len(y_c3)})")
print(f"  CNN-LSTM Val:        {cnn_val:.1f}%")
print(f"  CNN-LSTM Court P1:   {cnn_acc_c2:.1f}%")
print(f"  CNN-LSTM Court P2:   {cnn_acc_c3:.1f}%")
print(f"  Production model:    {winner}")
print("═"*60)

for fname in ['accel_svm_v4.pkl','accel_cnn_lstm_v4.h5',
              'svm_v4_confusion.png','cnnlstm_curves_v4.png',
              'accel_v4_comparison.png']:
    files.download(fname)
    print(f"  {fname}")

print(f"\n DONE — {winner} wins | Court P1: {acc_c2:.0f}% | Court P2: {acc_c3:.0f}%")