# -*- coding: utf-8 -*-
"""CNN-LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2K0MCUxKvdbTn_114hzHAh-ADg9DU6b

cell 1
"""

#   CNN-LSTM training camera
#   all data is normlised before training
#   11 joints used in training
#   [R_Shoulder, L_Shoulder, R_Elbow, L_Elbow, R_Wrist, L_Wrist,
#   R_Hip, L_Hip, R_Knee, L_Knee, Nose]


!pip install -q tensorflow scikit-learn scipy matplotlib seaborn

import os, zipfile
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.signal import resample
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Input, Reshape, Conv1D, MaxPooling1D,
                                     LSTM, Dense, Dropout, BatchNormalization)
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.utils import to_categorical
from google.colab import files

print("All imports done")

"""CELL 2"""

print("Upload TENNIS_CLEAN.zip now")
uploaded = files.upload()

zip_name = [f for f in uploaded.keys() if f.endswith('.zip')][0]
with zipfile.ZipFile(zip_name, 'r') as z:
    z.extractall("TENNIS_DATA")

print("Extracted folders:")
for item in os.listdir("TENNIS_DATA"):
    print(f"  {item}")

"""CELL 3"""

TARGET_FRAMES = 30
R_HIP_IDX = 6
L_HIP_IDX = 7

def load_folder(folder, label):
    X_list, y_list = [], []
    bad = 0
    for f in sorted(os.listdir(folder)):
        if not f.endswith(".npy"):
            continue
        data = np.load(os.path.join(folder, f))


        if data.ndim == 2:
            data = data.reshape(-1, 11, 2)


          if data.shape[0] != TARGET_FRAMES:
            data = resample(data, TARGET_FRAMES, axis=0)


        hip_mid = (data[:, R_HIP_IDX, :] + data[:, L_HIP_IDX, :]) / 2.0
        data = data - hip_mid[:, np.newaxis, :]


        data = data.reshape(TARGET_FRAMES, 22).astype(np.float32)
        X_list.append(data)
        y_list.append(label)

    return X_list, y_list


def find_folder(name):
    for root, dirs, _ in os.walk("TENNIS_DATA"):
        for d in dirs:
            if name in d:
                return os.path.join(root, d)
    return None

F_PATH = find_folder("forehand_v2")
B_PATH = find_folder("backhand_v3")
S_PATH = find_folder("serve_v3")

print(f"Forehand: {F_PATH}")
print(f"Backhand: {B_PATH}")
print(f"Serve:    {S_PATH}")

X, y = [], []
for path, label, name in [(F_PATH,0,"Forehand"),(B_PATH,1,"Backhand"),(S_PATH,2,"Serve")]:
    xf, yf = load_folder(path, label)
    X += xf
    y += yf
    print(f"  {name}: {len(xf)} clips loaded")

X = np.array(X)
y = np.array(y)
print(f"\n Raw dataset: {X.shape}  labels: {y.shape}")
print(f"   Class counts: F={np.sum(y==0)}  B={np.sum(y==1)}  S={np.sum(y==2)}")

"""CELL 4"""

X_train_orig, X_val, y_train_orig, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

def flip_horizontal(seq):
    flipped = seq.copy()
    flipped[:, 0::2] = -flipped[:, 0::2]
    return flipped

def add_noise(seq, scale=0.005):
    """Small random noise — prevents exact memorization"""
    return seq + np.random.normal(0, scale, seq.shape).astype(np.float32)

X_aug, y_aug = [], []
for seq, label in zip(X_train_orig, y_train_orig):

    flipped = flip_horizontal(seq)
    X_aug.append(flipped)
    y_aug.append(1 if label==0 else (0 if label==1 else 2))


    X_aug.append(add_noise(seq))
    y_aug.append(label)


    X_aug.append(add_noise(flipped))
    y_aug.append(1 if label==0 else (0 if label==1 else 2))

X_aug = np.array(X_aug)
y_aug = np.array(y_aug)

X_train = np.concatenate([X_train_orig, X_aug])
y_train = np.concatenate([y_train_orig, y_aug])


idx = np.random.permutation(len(X_train))
X_train, y_train = X_train[idx], y_train[idx]

print(f" Train: {X_train.shape}  Val: {X_val.shape}")
print(f"   Train: F={np.sum(y_train==0)}  B={np.sum(y_train==1)}  S={np.sum(y_train==2)}")
print(f"   Val:   F={np.sum(y_val==0)}  B={np.sum(y_val==1)}  S={np.sum(y_val==2)}")

"""CELL 5"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.optimizers import Adam
import tensorflow as tf


model = Sequential([
    Input(shape=(30, 22)),

    LSTM(64, return_sequences=True),
    Dropout(0.3),

    LSTM(32, return_sequences=False),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()
print(" Model built")

"""CELL 6"""

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.regularizers import l2

callbacks = [
    EarlyStopping(patience=25, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6, verbose=1)
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=200,
    batch_size=8,
    callbacks=callbacks,
    verbose=1
)

print(f"\n Training complete")
print(f"   Best val accuracy: {max(history.history['val_accuracy']):.3f}")

"""CELL 7"""

y_pred = np.argmax(model.predict(X_val), axis=1)
LABEL_NAMES = ["Forehand", "Backhand", "Serve"]

print("="*50)
print("CLASSIFICATION REPORT")
print("="*50)
print(classification_report(y_val, y_pred, target_names=LABEL_NAMES))

# Confusion matrix
cm = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=LABEL_NAMES, yticklabels=LABEL_NAMES,
            linewidths=0.5, linecolor='gray')
plt.title("CNN-LSTM Confusion Matrix (New Model)", fontsize=13, fontweight='bold')
plt.ylabel("True Label", fontsize=11)
plt.xlabel("Predicted Label", fontsize=11)
plt.tight_layout()
plt.savefig("confusion_matrix_cnn_lstm.png", dpi=150)
plt.show()
print(" Saved: confusion_matrix_cnn_lstm.png")

"""CELL 8"""

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].plot(history.history['accuracy'],     label='Train', color='#0050FF', linewidth=2)
axes[0].plot(history.history['val_accuracy'], label='Val',   color='#00C850', linewidth=2)
axes[0].set_title("Accuracy", fontsize=12, fontweight='bold')
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Accuracy")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['loss'],     label='Train', color='#0050FF', linewidth=2)
axes[1].plot(history.history['val_loss'], label='Val',   color='#C85000', linewidth=2)
axes[1].set_title("Loss", fontsize=12, fontweight='bold')
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.suptitle("CNN-LSTM Training History", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("training_curves.png", dpi=150)
plt.show()
print(" Saved: training_curves.png")

"""CELL 9"""

model.save("tennis_cnn_lstm_v1.h5")
print(" Model saved: tennis_cnn_lstm_v1.h5")

# Download all outputs
for fname in ["tennis_cnn_lstm_v1.h5", "confusion_matrix_cnn_lstm.png", "training_curves.png"]:
    files.download(fname)
    print(f"  Downloading: {fname}")

print("\n ALL DONE — You now have your CNN-LSTM model!")

"""CELL 10"""

import numpy as np

print("="*60)
print("DATA DIAGNOSTIC")
print("="*60)


print(f"\n1. Raw X shape: {X.shape}")
print(f"   Labels: F={np.sum(y==0)}  B={np.sum(y==1)}  S={np.sum(y==2)}")

print(f"\n2. Sample values from X[0] (first forehand clip, first 3 frames):")
print(X[0][:3])

print(f"\n3. Are any clips identical? (checking for duplicates)")

diffs = [np.mean(np.abs(X[0] - X[i])) for i in range(1, len(X))]
near_zero = sum(1 for d in diffs if d < 0.001)
print(f"   Clips nearly identical to X[0]: {near_zero}")

print(f"\n4. Value ranges per class:")
for label, name in [(0,"Forehand"),(1,"Backhand"),(2,"Serve")]:
    clips = X[y==label]
    print(f"   {name}: min={clips.min():.4f}  max={clips.max():.4f}  mean={clips.mean():.4f}  std={clips.std():.4f}")

print(f"\n5. Are Forehand and Backhand clips distinguishable?")
fh = X[y==0].mean(axis=0)
bh = X[y==1].mean(axis=0)
diff = np.mean(np.abs(fh - bh))
print(f"   Mean absolute difference between avg Forehand vs Backhand: {diff:.6f}")
print(f"   (If this is near 0, the classes look identical to the model)")

print(f"\n6. Train/Val split check:")
print(f"   X_train: {X_train.shape}  y_train counts: F={np.sum(y_train==0)}  B={np.sum(y_train==1)}  S={np.sum(y_train==2)}")
print(f"   X_val:   {X_val.shape}    y_val counts:   F={np.sum(y_val==0)}    B={np.sum(y_val==1)}    S={np.sum(y_val==2)}")

print(f"\n7. Sample forehand clip wrist trajectory (joint 0, x coord):")
print(np.round(X[y==0][0][:, 0], 4))

print(f"\n8. Sample backhand clip wrist trajectory (joint 0, x coord):")
print(np.round(X[y==1][0][:, 0], 4))

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from google.colab import files


import os
if not os.path.exists("X.npy"):
    print("Upload X.npy and y.npy")
    uploaded = files.upload()

X = np.load("X.npy")
y = np.load("y.npy")

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")


X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42,
    stratify=y if y.ndim == 1 else np.argmax(y, axis=1)
)


preds = model.predict(X_val, verbose=0)
y_pred = np.argmax(preds, axis=1)


if y_val.ndim > 1:
    y_true = np.argmax(y_val, axis=1)
else:
    y_true = y_val.astype(int)


cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Forehand', 'Backhand', 'Serve'],
            yticklabels=['Forehand', 'Backhand', 'Serve'],
            linewidths=0.5)
plt.title('CNN-LSTM Confusion Matrix — Validation Set', fontsize=13, pad=15)
plt.ylabel('Actual Label', fontsize=11)
plt.xlabel('Predicted Label', fontsize=11)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

print("\n" + classification_report(
    y_true, y_pred,
    target_names=['Forehand', 'Backhand', 'Serve']
))

files.download('confusion_matrix.png')
print(" Saved → confusion_matrix.png")